all:
	gri logo
	mv logo.ps logo.eps
	gri version-diagram-2.2
	convert version-diagram-2.2.ps version-diagram-2.2.gif
	mv version-diagram-2.2.ps version-diagram-2.2.eps
	gri version-diagram-2.4
	convert version-diagram-2.4.ps version-diagram-2.4.gif
	mv version-diagram-2.4.ps version-diagram-2.4.eps
clean:
	rm -rf logo.eps version-diagram*.eps *~
