#if !defined(_tags_h_)

#define _tags_hh_
#include "gr.hh"
bool
cdCmd(void),
closeCmd(void),
convert_col_fro_pol_to_recCmd(void),
convert_col_fro_rec_to_polCmd(void),
convert_col_to_gridCmd(void),
convert_col_to_splineCmd(void),
convert_grid_to_columnsCmd(void),
convert_grid_to_imageCmd(void),
convert_image_to_gridCmd(void),
debugCmd(void),
deleteCmd(void),
differentiateCmd(void),
draw_arrow_from_toCmd(void),
draw_arrowsCmd(void),
draw_axes_if_needed(void),
draw_axesCmd(void),
draw_boxCmd(void),
draw_box_filledCmd(void),
draw_circleCmd(void),
draw_contourCmd(void),
draw_curveCmd(void),
draw_gri_logoCmd(void),
draw_gridCmd(void),
draw_imageCmd(void),
draw_image_histogramCmd(void),
draw_image_paletteCmd(void),
draw_isopycnalCmd(void),
draw_labelCmd(void),
draw_line_from_toCmd(void),
draw_linesCmd(void),
draw_patchesCmd(void),
draw_polygonCmd(void),
draw_symbolCmd(void),
draw_titleCmd(void),
draw_valuesCmd(void),
draw_x_axisCmd(void),
draw_x_box_plotCmd(void),
draw_y_axisCmd(void),
draw_y_box_plotCmd(void),
draw_zero_lineCmd(void),
expectingCmd(void),
filter_columnCmd(void),
filter_gridCmd(void),
filter_imageCmd(void),
flipCmd(void),
get_envCmd(void),
healCmd(void),
helpCmd(void),
ignoreCmd(void),
inputCmd(void),
insertCmd(void),
interpolateCmd(void),
listCmd(void),
lsCmd(void),
maskCmd(void),
newCmd(void),
new_pageCmd(void),
nullCmd(void),
openCmd(void),
postscriptCmd(void),
pwdCmd(void),
queryCmd(void),
quitCmd(void),
read_colornamesCmd(void),
read_columnsCmd(void),
read_from_filenameCmd(void),
read_gridCmd(void),
read_imageCmd(void),
read_image_colorscaleCmd(void),
read_image_grayscaleCmd(void),
read_image_maskCmd(void),
read_image_mask_rasterfileCmd(void),
read_image_pgmCmd(void),
read_image_rasterfileCmd(void),
read_synonym_or_variableCmd(void),
read_lineCmd(void),
regressCmd(void),
reorder_columnsCmd(void),
rpnfunctionCmd(void),
rescaleCmd(void),
rewindCmd(void),
set_axes_styleCmd(void),
set_arrow_sizeCmd(void),
set_arrow_typeCmd(void),
set_beepCmd(void),
set_bounding_boxCmd(void),
set_clipCmd(void),
set_colorCmd(void),
set_contour_formatCmd(void),
set_contour_labelCmd(void),
set_contour_labelsCmd(void),
set_dashCmd(void),
set_environment(void),
set_error_actionCmd(void),
set_flagCmd(void),
set_font_colorCmd(void),
set_font_encodingCmd(void),
set_font_sizeCmd(void),
set_font_toCmd(void),
set_graylevelCmd(void),
set_grid_missingCmd(void),
set_image_colorscaleCmd(void),
set_image_grayscale_using_hist(void),
set_image_grayscaleCmd(void),
set_image_missingCmd(void),
set_image_rangeCmd(void),
set_ignore_initial_newlineCmd(void),
set_ignoreCmd(void),
set_input_data_windowCmd(void),
set_input_data_separatorCmd(void),
set_line_capCmd(void),
set_line_joinCmd(void),
set_line_widthCmd(void),
set_missing_valueCmd(void),
set_pageCmd(void),
set_postscript_filenameCmd(void),
set_symbol_sizeCmd(void),
set_ticsCmd(void),
set_tic_sizeCmd(void),
set_u_scaleCmd(void),
set_v_scaleCmd(void),
set_traceCmd(void),
set_x_axisCmd(void),
set_x_formatCmd(void),
set_x_gridCmd(void),
set_x_marginCmd(void),
set_x_nameCmd(void),
set_x_sizeCmd(void),
set_x_typeCmd(void),
set_y_axisCmd(void),
set_y_axis_labelCmd(void),
set_y_axisCmd(void),
set_y_formatCmd(void),
set_y_gridCmd(void),
set_y_marginCmd(void),
set_y_nameCmd(void),
set_y_sizeCmd(void),
set_y_typeCmd(void),
set_z_missingCmd(void),
show_allCmd(void),
show_axesCmd(void),
show_colorCmd(void),
show_colornamesCmd(void),
show_columnsCmd(void),
show_expression_or_stringCmd(void),
show_flagsCmd(void),
show_gridCmd(void),
show_hintCmd(void),
show_imageCmd(void),
show_licenseCmd(void),
show_miscCmd(void),
show_next_lineCmd(void),
show_stopwatchCmd(void),
show_synonymsCmd(void),
show_timeCmd(void),
show_tracebackCmd(void),
show_variablesCmd(void),
smoothCmd(void),
skipCmd(void),
sprintfCmd(void),
stateCmd(void),
systemCmd(void),
superuserCmd(void),
whileCmd(void),
writeCmd(void);


typedef struct {
    bool(*fcn) ();
    const char *name;
}               C_FCN;

C_FCN           c_fcn[] = {
{cdCmd, "cdCmd"},
{closeCmd, "closeCmd"},
{convert_col_to_gridCmd, "convert_columns_to_gridCmd"},
{convert_col_to_splineCmd, "convert_columns_to_splineCmd"},
{convert_grid_to_columnsCmd, "convert_grid_to_columnsCmd"},
{convert_grid_to_imageCmd, "convert_grid_to_imageCmd"},
{convert_image_to_gridCmd, "convert_image_to_gridCmd"},
{debugCmd, "debugCmd"},
{deleteCmd, "deleteCmd"},
{differentiateCmd, "differentiateCmd"},
{draw_arrow_from_toCmd, "draw_arrow_from_toCmd"},
{draw_arrowsCmd, "draw_arrowsCmd"},
{draw_axes_if_needed, "draw_axes_if_needed"},
{draw_axesCmd, "draw_axesCmd"},
{draw_boxCmd, "draw_boxCmd"},
{draw_box_filledCmd, "draw_box_filledCmd"},
{draw_circleCmd, "draw_circleCmd"},
{draw_contourCmd, "draw_contourCmd"},
{draw_curveCmd, "draw_curveCmd"},
{draw_gri_logoCmd, "draw_gri_logoCmd"},
{draw_gridCmd, "draw_gridCmd"},
{draw_imageCmd, "draw_imageCmd"},
{draw_image_histogramCmd, "draw_image_histogramCmd"},
{draw_image_paletteCmd, "draw_image_paletteCmd"},
{draw_isopycnalCmd, "draw_isopycnalCmd"},
{draw_labelCmd, "draw_labelCmd"},
{draw_line_from_toCmd, "draw_line_from_toCmd"},
{draw_linesCmd, "draw_linesCmd"},
{draw_patchesCmd, "draw_patchesCmd"},
{draw_polygonCmd, "draw_polygonCmd"},
{draw_symbolCmd, "draw_symbolCmd"},
{draw_titleCmd, "draw_titleCmd"},
{draw_valuesCmd, "draw_valuesCmd"},
{draw_x_axisCmd, "draw_x_axisCmd"},
{draw_x_box_plotCmd, "draw_x_box_plotCmd"},
{draw_y_axisCmd, "draw_y_axisCmd"},
{draw_y_box_plotCmd, "draw_y_box_plotCmd"},
{draw_zero_lineCmd, "draw_zero_lineCmd"},
{expectingCmd, "expectingCmd"},
{filter_columnCmd, "filter_columnCmd"},
{filter_gridCmd, "filter_gridCmd"},
{filter_imageCmd, "filter_imageCmd"},
{flipCmd, "flipCmd"},
{get_envCmd, "get_envCmd"},
{healCmd, "healCmd"},
{helpCmd, "helpCmd"},
{ignoreCmd, "ignoreCmd"},
{inputCmd, "inputCmd"},
{insertCmd, "insertCmd"},
{interpolateCmd, "interpolateCmd"},
{listCmd, "listCmd"},
{lsCmd, "lsCmd"},
{maskCmd, "maskCmd"},
{newCmd, "newCmd"},
{new_pageCmd, "new_pageCmd"},
{nullCmd, "nullCmd"},
{openCmd, "openCmd"},
{postscriptCmd, "postscriptCmd"},
{pwdCmd, "pwdCmd"},
{queryCmd, "queryCmd"},
{quitCmd, "quitCmd"},
{read_colornamesCmd, "read_colornamesCmd"},
{read_columnsCmd, "read_columnsCmd"},
{read_from_filenameCmd, "read_from_filenameCmd"},
{read_gridCmd, "read_gridCmd"},
{read_imageCmd, "read_imageCmd"},
{read_image_colorscaleCmd, "read_image_colorscaleCmd"},
{read_image_grayscaleCmd, "read_image_grayscaleCmd"},
{read_image_maskCmd, "read_image_maskCmd"},
{read_image_mask_rasterfileCmd, "read_image_mask_rasterfileCmd"},
{read_image_pgmCmd, "read_image_pgmCmd"},
{read_image_rasterfileCmd, "read_image_rasterfileCmd"},
{read_synonym_or_variableCmd, "read_synonym_or_variableCmd"},
{read_lineCmd, "read_lineCmd"},
{regressCmd, "regressCmd"},
{reorder_columnsCmd, "reorder_columnsCmd"},
{rpnfunctionCmd, "rpnfunctionCmd"},
{rescaleCmd, "rescaleCmd"},
// resizeCmd is written in Gri
{rewindCmd, "rewindCmd"},
{set_axes_styleCmd, "set_axes_styleCmd"},
{set_arrow_sizeCmd, "set_arrow_sizeCmd"},
{set_arrow_typeCmd, "set_arrow_typeCmd"},
{set_beepCmd, "set_beepCmd"},
{set_bounding_boxCmd, "set_bounding_boxCmd"},
{set_clipCmd, "set_clipCmd"},
{set_colorCmd, "set_colorCmd"},
{set_contour_formatCmd, "set_contour_formatCmd"},
{set_contour_labelCmd, "set_contour_labelCmd"},
{set_contour_labelsCmd, "set_contour_labelsCmd"},
{set_dashCmd, "set_dashCmd"},
{set_environment, "set_environment"},
{set_error_actionCmd, "set_error_actionCmd"},
{set_flagCmd, "set_flag"},
{set_font_colorCmd, "set_font_colorCmd"},
{set_font_encodingCmd, "set_font_encodingCmd"},
{set_font_sizeCmd, "set_font_sizeCmd"},
{set_font_toCmd, "set_font_toCmd"},
{set_graylevelCmd, "set_graylevelCmd"},
{set_grid_missingCmd, "set_grid_missingCmd"},
{set_image_colorscaleCmd, "set_image_colorscaleCmd"},
{set_image_grayscale_using_hist, "set_image_grayscale_using_histogramCmd"},
{set_image_grayscaleCmd, "set_image_grayscaleCmd"},
{set_image_missingCmd, "set_image_missingCmd"},
{set_image_rangeCmd, "set_image_rangeCmd"},
{set_ignore_initial_newlineCmd, "set_ignore_initial_newlineCmd"},
{set_ignoreCmd, "set_ignoreCmd"},
{set_input_data_windowCmd, "set_input_data_windowCmd"},
{set_input_data_separatorCmd, "set_input_data_separatorCmd"},
{set_line_capCmd, "set_line_capCmd"}, 
{set_line_joinCmd, "set_line_joinCmd"}, 
{set_line_widthCmd, "set_line_widthCmd"},
{set_missing_valueCmd, "set_missing_valueCmd"},
{set_pageCmd, "set_pageCmd"},
{set_postscript_filenameCmd, "set_postscript_filenameCmd"},
{set_symbol_sizeCmd, "set_symbol_sizeCmd"},
{set_ticsCmd, "set_ticsCmd"},
{set_tic_sizeCmd, "set_tic_sizeCmd"},
{set_u_scaleCmd, "set_u_scaleCmd"},
{set_v_scaleCmd, "set_v_scaleCmd"},
{set_traceCmd, "set_traceCmd"},
{set_x_axisCmd, "set_x_axisCmd"},
{set_x_formatCmd, "set_x_formatCmd"},
{set_x_gridCmd, "set_x_gridCmd"},
{set_x_marginCmd, "set_x_marginCmd"},
{set_x_nameCmd, "set_x_nameCmd"},
{set_x_sizeCmd, "set_x_sizeCmd"},
{set_x_typeCmd, "set_x_typeCmd"},
{set_y_axisCmd, "set_y_axisCmd"},
{set_y_axis_labelCmd, "set_y_axis_labelCmd"},
{set_y_axisCmd, "set_y_axisCmd"},
{set_y_formatCmd, "set_y_formatCmd"},
{set_y_gridCmd, "set_y_gridCmd"},
{set_y_marginCmd, "set_y_marginCmd"},
{set_y_nameCmd, "set_y_nameCmd"},
{set_y_sizeCmd, "set_y_sizeCmd"},
{set_y_typeCmd, "set_y_typeCmd"},
{set_z_missingCmd, "set_z_missingCmd"},
{show_allCmd, "show_allCmd"},
{show_axesCmd, "show_axesCmd"},
{show_colorCmd, "show_colorCmd"},
{show_colornamesCmd, "show_colornamesCmd"},
{show_columnsCmd, "show_columnsCmd"},
{show_expression_or_stringCmd, "show_expression_or_stringCmd"},
{show_flagsCmd, "show_flagsCmd"},
{show_gridCmd, "show_gridCmd"},
{show_hintCmd, "show_hintCmd"},
{show_imageCmd, "show_imageCmd"},
{show_licenseCmd, "show_licenseCmd"},
{show_miscCmd, "show_miscCmd"},
{show_next_lineCmd, "show_next_lineCmd"},
{show_stopwatchCmd, "show_stopwatchCmd"},
{show_synonymsCmd, "show_synonymsCmd"},
{show_timeCmd, "show_timeCmd"},
{show_tracebackCmd, "show_tracebackCmd"},
{show_variablesCmd, "show_variablesCmd"},
{smoothCmd, "smoothCmd"},
{skipCmd, "skipCmd"},
{sprintfCmd, "sprintfCmd"},
{stateCmd, "stateCmd"},
{systemCmd, "systemCmd"},
{superuserCmd, "superuserCmd"},
{whileCmd, "whileCmd"},
{writeCmd, "writeCmd"},
{0, ""}
};
#endif				// _tags_hh
