#!/bin/sh
#HOW TO INSTALL ON SOURCEFORGE:

export CVS_RSH=ssh
export CVSROOT=dankelley@cvs.gri.sourceforge.net:/cvsroot/gri
export PHP="index.php bugs.php contact.php developers.php docs.php download.php subroutines.php news.php"
export PNG="bugs.png contact.png developers.png docs.png download.png main.png news.png"

scp $PHP $PNG dankelley@gri.sourceforge.net:/home/groups/g/gr/gri/htdocs

# pre-releases
# scp <> dankelley@gri.sourceforge.net:/home/groups/g/gr/gri/htdocs/pre-releases
# ssh dankelley@gri.sf.net ; cd /home/groups/g/gr/gri/htdocs ; edit stuff.
