.TH GRI 1
.SH NAME 
gri \- scientific graphics language
.SH SYNOPSIS
.B gri
#         Typed commands yield PS file
.I gri-00.ps
.br
.B gri foo.gri
# Script
.I foo.gri
yields PS file
.I foo.ps

.SH DESCRIPTION

Gri is a programming language for scientific graphics.  It can make
x-y graphs, contour-graphs, and image graphs.  In addition, Gri has a
full suite of low-level graphical elements and sufficient programming
capabilities (loops, subroutines, etc) to permit complex
customization.

Gri is not a point-click application.  In some ways it is analogous to
TeX; in both cases extensive power rewards tolerance of a modest
learning curve.

.SH FULL DOCUMENTATION

This manpage is intended merely as a pointer to the main
documentation, which you may find at:

.SS The INFO manual
is accessed by typing
.B info gri
or by accessing the 'info' node in Emacs or in other standard ways.

.SS The HTML manual
is located at
.B /usr/doc/gri-VERSION/html/index.html
where 
.B VERSION
is the version number of the Gri installed on your machine.
The 
.I html
FAQ is located at
.B /usr/doc/gri-VERSION/html/FAQ.html

.SS PostScript reference cards
are at
.B /usr/doc/gri-VERSION/refcard.ps
(overall reference and quick introduction) and 
.B /usr/doc/gri-VERSION/cmdrefcard.ps
(reference to commands).

.SH EMACS SUPPORT

An 
.I emacs
mode is provided with Gri.  It is at
.B /usr/share/emacs/site-lisp/gri-mode.el
and is fully described in a chapter in the manual.

.SH SEE ALSO
Related programs
.B gri_unpage
and 
.B gri_merge
for working with PostScript output from Gri.

.SH AUTHORS
Gri (c) 2000 Dan Kelley <Dan.Kelley@Dal.CA> and Peter S Galbraith
<psg@debian.org>.
