#!/usr/bin/perl
die "Usage: gri2html file.gri" if ($#ARGV !=0);
open(IN,  "$ARGV[0].gri")   || die "Can't open `$ARGV[0].gri'  for input\n";
open(OUT, ">$ARGV[0].html") || die "Can't open `$ARGV[0].html' for output\n";

print OUT "<html>\n";
print OUT "<head>\n";
print OUT "<title>$ARGV[0].gri</title>\n";
print OUT "</head>\n";
print OUT "<body>\n";
print OUT "<pre>\n";

while(<IN>) {
    s,//(.*),<i>//$1</i>,;
    s,"(.*)",<u>"$1"</u>,g;
    print OUT "$_";
}
print OUT "</pre>\n";
print OUT "</body>\n";
print OUT "</html>\n";
